name: Deploy Theme to GoDaddy Staging

on:
  push:
    branches:
      - main # Change to 'staging' if your main branch is named staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy MindShows Theme via Rsync over SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GODADDY_PRIVATE_KEY }}
          ARGS: "-rlptgoD --delete --exclude='.git*' --exclude='.github*'"
          REMOTE_HOST: "1243931.eu15.ssh.myftpupload.com"
          REMOTE_USER: "git_deployer_36e43e8b24_1243931"
          PORT: "22"
          TARGET: "html/wp-content/themes/MindShows/"